imports:
  - {resource: common-mark.yml}
  - {resource: converters.yml}
  - {resource: html-to-markdown.yml}

parameters:
  env(APP_SECRET): 'qwoirekjwruskdfj'
framework:
  secret: '%env(APP_SECRET)%'
  session: ~
twig: ~
services:
  _defaults:
    autoconfigure: true
    autowire: true
  logger:
    alias: Psr\Log\NullLogger
  Psr\Log\NullLogger: ~
  TJM\Wiki\Wiki:
    arguments: ['%kernel.project_dir%/wiki']
  TJM\WikiSite\WikiSite:
    arguments:
      $opts:
        converters:
          - '@TJM\WikiSite\FormatConverter\HtmlToMarkdownConverter'
          - '@TJM\WikiSite\FormatConverter\MarkdownToCleanMarkdownConverter'
          - '@TJM\WikiSite\FormatConverter\MarkdownToHtmlConverter'
        router: '@router'
        twig: '@twig'
    tags:
      - 'controller.service_arguments'
      -
        event: 'kernel.exception'
        method: 'handleException'
        name: 'kernel.event_listener'
